### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by temass1997**
Hi. How to set proxy for socketChannel ? 
For the answer I will present 1btc

### CODE REVIEW

**Comment by barb1turat** [comment]
The developer of this project is an idiot, he used java.nio.channels.SocketChannel they can not be attached to a proxy. Developer you bastard, burn you in hell!

**Comment by GreenSeed** [comment]
> Hi. How to set proxy for socketChannel ?
> For the answer I will present 1btc
Are you still intrested in proxy?
Tell me your telegram

**Comment by applke** [comment]
@greensockss

> > Hi. How to set proxy for socketChannel ?
> > For the answer I will present 1btc
> > Are you still intrested in proxy?
> > Tell me your telegram

**Comment by applke** [comment]
I can help you with this solution!

**Pull request closed without merging**
